apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }} 
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: {{ $.Values.Domain | quote }}
      http:
        paths:
          - path: $.Values.Path 
            backend:
              serviceName: {{ include "helm.fullname" . }} 
              servicePort: {{ .Values.service.port }}
  tls:
    - hosts:
      - $.Values.Domain 
      secretName: {{ $.Values.Domain }}
