name: Build & Deploy App

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the tagged Docker image
        run: docker build -t sarathp88/go-k8s-helm:${{ github.sha }} .
      - name: Push the tagged Docker image
        run: docker push sarathp88/go-k8s-helm:${{ github.sha }}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag sarathp88/go-k8s-helm:latest
      - name: Push the latest Docker image
        run: docker push sarathp88/go-k8s-helm:latest
      - name: install helm
        uses: Azure/setup-helm@v1
      - name: validate Chart
        run: |
          helm lint ./helm
      - name: Helm Package
        run: |
          helm package --app-version=${{ github.sha }} ./helm
      - name: Install Helm release
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_FILE }}'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          helm upgrade --install --set image.tag=${{ github.sha }} ${{github.repository}} /home/runner/work/go-k8s-helm/go-k8s-helm/go-k8s-helm-1.0.0.tgz
