name: Build & Deploy App

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag sarathp88/go-k8s-helm:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push sarathp88/go-k8s-helm:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag sarathp88/go-k8s-helm:latest
      - name: Push the latest Docker image
        run: docker push sarathp88/go-k8s-helm:latest
